disable_classroom = 1

dont_enforce_access_settings = 0
pawtucket_requires_login = 0

clean_urls = 1

do_content_caching = 0
content_caching_dir = <ca_app_dir>/tmp

use_identifiers_in_urls = 0

front_page_set_code = objetos_destacados

export_formats = {
	ca_objects = {
		basic_excel = {
			name = Excel (información básica),
			type = xlsx,
			columns = {
				Identificador = {
					template = ^ca_objects.idno
				},
				Número_Original = {
					template = ^ca_objects.numero_original
				},
				Objeto = {
					template = ^ca_objects.preferred_labels.name
				},
				Tipo = {
					template = ^ca_objects.tipo_objeto_vocab
				},
				Material = {
					template = ^ca_objects.material
				},
				Descripción = {
					template = ^ca_objects.descripcion
				},
				Colección = {
					template = ^ca_collections.preferred_labels.name
				},
				Colector = {
					template = ^ca_entities.preferred_labels.displayname
				},
				Procedencia = {
					template = ^ca_places.preferred_labels.name
				}
			}
		}
	}
}
