# Theme-specific asset (js, css) configuration

#minification = 1
minification = 0

themePackages = {
        # -----------------------
        pawtucket = {
                css = css/main.css:100,
                fonts = css/fonts.css,
                fontAwesome = css/Font-Awesome/css/font-awesome.css,
                themecss = css/theme.css:200,
                homebibsite = css/home_bibsite.css:300,
                # Agregamos tu archivo con prioridad 400 para que pise todo lo anterior
                customcss = css/custom.css:400,
                scrollTo = js/jquery.scrollTo.js
        }
        # -----------------------
}

themeLoadSets = {
        #
        # Libraries listed in "_default" are always loaded
        #
        _default = [
                pawtucket/css, 
                pawtucket/fonts, 
                pawtucket/fontAwesome, 
                pawtucket/themecss, 
                pawtucket/homebibsite, 
                pawtucket/customcss, 
                pawtucket/scrollTo
        ]
}
