cache_timeout = 0

menubarFacetGroup = panel

browseTypes = {
	objects = {
		displayName = _("Objetos"),
		labelSingular = _("objeto"),
		labelPlural = _("objetos"),
		table = ca_objects,
		restrictToTypes = [],
		availableFacets = [tipo,material,manufactura,coleccion,colector,lugar,epoca,grupo,comunidad],
		facetGroup = filter,
		views = {
			images = {},
			list = {}
		},
		sortBy = {
			Relevance = _natural,
			Título = ca_object_labels.name_sort,
			Identificador = ca_objects.idno
		},
		sortDirection = {
			Relevance = asc,
			Título = asc,
			Identificador = asc
		},
		sortControlType = dropdown,

		facets = {
			tipo = {
				type = attribute,
				element_code = tipo_objeto_vocab,
				group_mode = none,
				label_singular = _("tipo de objeto"),
				label_plural = _("tipos de objeto"),
				order_by_count = 1
			},
			material = {
				type = attribute,
				element_code = material,
				group_mode = none,
				label_singular = _("material"),
				label_plural = _("materiales"),
				order_by_count = 1
			},
			manufactura = {
				type = attribute,
				element_code = manufactura,
				group_mode = none,
				label_singular = _("técnica de manufactura"),
				label_plural = _("técnicas de manufactura"),
				order_by_count = 1
			},
			coleccion = {
				type = collections,
				group_mode = none,
				label_singular = _("colección"),
				label_plural = _("colecciones"),
				order_by_count = 1,
				show_all_when_first_facet = 0,
				maximumBrowseDepth = 2
			},
			colector = {
				type = entities,
				entityTypes = [individuo],
				group_mode = alphabetical,
				label_singular = _("colector"),
				label_plural = _("colectores"),
				order_by_count = 1
			},
			lugar = {
				type = places,
				group_mode = none,
				label_singular = _("procedencia geográfica"),
				label_plural = _("procedencias geográficas"),
				order_by_count = 1,
				placeTypes = [pais,provincia,localidad,sitio],
				maximumBrowseDepth = 2
			},
			epoca = {
				type = attribute,
				element_code = epoca,
				group_mode = none,
				label_singular = _("época"),
				label_plural = _("épocas"),
				order_by_count = 1
			},
			grupo = {
				type = attribute,
				element_code = grupo,
				group_mode = none,
				label_singular = _("grupo étnico"),
				label_plural = _("grupos étnicos"),
				order_by_count = 1
			},
			comunidad = {
				type = attribute,
				element_code = comunidad,
				group_mode = none,
				label_singular = _("comunidad"),
				label_plural = _("comunidades"),
				order_by_count = 1
			}
		}
	},

	collections = {
		displayName = _("Colecciones"),
		labelSingular = _("colección"),
		labelPlural = _("colecciones"),
		table = ca_collections,
		restrictToTypes = [coleccion, subcoleccion, inventario],
		availableFacets = [tipo_coleccion],
		facetGroup = filter,
		views = {
			list = {}
		},
		sortBy = {
			Relevance = _natural,
			Título = ca_collection_labels.name_sort
		},
		sortDirection = {
			Relevance = asc,
			Título = asc
		},
		sortControlType = dropdown,
		facets = {
			tipo_coleccion = {
				type = fieldList,
				field = type_id,
				group_mode = none,
				label_singular = _("tipo"),
				label_plural = _("tipos"),
				order_by_count = 1
			}
		}
	},

	entities = {
		displayName = _("Colectores"),
		labelSingular = _("colector"),
		labelPlural = _("colectores"),
		table = ca_entities,
		restrictToTypes = [individuo],
		availableFacets = [],
		facetGroup = filter,
		views = {
			list = {}
		},
		sortBy = {
			Relevance = _natural,
			Nombre = ca_entity_labels.surname;ca_entity_labels.forename
		},
		sortControlType = dropdown
	}
}

views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	}
}

defaultHitsPerBlock = 36
sortControlType = dropdown
result_col_class = col-xs-9 col-sm-9 col-md-9 col-lg-9
refine_col_class = col-xs-3 col-sm-3 col-md-3 col-lg-3
