<?php
# themes/filo/conf/front.conf

# Set de objetos destacados para el carrusel
front_page_set_code = 53

# Título de la sección de conjuntos destacados
front_page_set_title = "Conjuntos destacados"

# Mostrar buscador avanzado
front_page_show_search_form = 0

# Deshabilitar secciones adicionales
front_page_sections = {
}
?>
